import { expect, test } from "bun:test";
import { createHash } from "node:crypto";
import { mkdtemp, mkdir, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import reference from "./fixtures/memory-reference.json";
import {
  applyExtractedMemories,
  buildEpisodeUserPrompt,
  buildExtractionUserPrompt,
  gatherExtractionMemories,
  getMemoryEpisodeInterval,
  isMemorableExchange,
  parseEpisodeNarrative,
  parseExtractedMemories,
} from "../src/memory-learning";
import { appendMemoryFact, readMemoryTree } from "../src/memory-files";
import {
  MEMORY_EXTRACTION_SYSTEM_PROMPT,
  MEMORY_EPISODE_SYSTEM_PROMPT,
  MEMORY_SYNTHESIS_SYSTEM_PROMPT,
  MEMORY_VERIFICATION_SYSTEM_PROMPT,
} from "../src/memory-prompts";

// These expected values were executed against the independently hashed ecc8113
// runtime, not generated by our implementation.
for (const fixture of reference.eligibility) {
  test(`reference eligibility: ${JSON.stringify(fixture.user)}`, () => {
    expect(isMemorableExchange(fixture.user)).toBe(fixture.expected);
  });
}

for (const [index, fixture] of reference.extraction.entries()) {
  test(`reference extraction protocol ${index + 1}`, () => {
    expect(fixture.expected).toEqual(parseExtractedMemories(fixture.raw, fixture.existing));
  });
}

for (const fixture of reference.intervals) {
  test(`reference episode interval: ${JSON.stringify(fixture.value)}`, () => {
    expect(
      getMemoryEpisodeInterval(
        fixture.value === null ? {} : { SAND_MEMORY_EPISODE_INTERVAL: fixture.value }
      )
    ).toBe(fixture.expected);
  });
}

for (const fixture of reference.selection) {
  test(`reference extraction context: ${fixture.name}`, async () => {
    const root = await mkdtemp(join(tmpdir(), "memory-selection-"));
    try {
      for (const [name, raw] of Object.entries(fixture.files)) {
        if (typeof raw !== "string") continue;
        const file = join(root, name);
        await mkdir(dirname(file), { recursive: true });
        await writeFile(file, raw);
      }
      expect(gatherExtractionMemories(await readMemoryTree(root), fixture.query)).toEqual(
        fixture.expected
      );
    } finally {
      await rm(root, { recursive: true, force: true });
    }
  });
}

test("all four inference prompts match the captured source with the assistant name adapted", () => {
  const prompts = {
    buildExtractionSystemPrompt: MEMORY_EXTRACTION_SYSTEM_PROMPT,
    buildEpisodeSystemPrompt: MEMORY_EPISODE_SYSTEM_PROMPT,
    synthesisSystemPrompt: MEMORY_SYNTHESIS_SYSTEM_PROMPT,
    verificationSystemPrompt: MEMORY_VERIFICATION_SYSTEM_PROMPT,
  };
  for (const [key, prompt] of Object.entries(prompts)) {
    expect(createHash("sha256").update(prompt).digest("hex")).toBe(
      reference.promptHashes[key as keyof typeof prompts]
    );
  }
});

test("corrections remove only supplied facts, preserve unrelated Markdown, and persist notes once", async () => {
  const root = await mkdtemp(join(tmpdir(), "memory-correction-"));
  const now = new Date("2026-09-12T12:00:00Z");
  try {
    await writeFile(
      join(root, "profile.md"),
      "# Keep this heading\nManual prose.\n- (2020-01-01) Lives in Boston.\n"
    );
    await appendMemoryFact(root, "Unrelated protected preference.", "profile", now);
    const existing = ["Lives in Boston."];
    const parsed = parseExtractedMemories(
      "remove: Lives in Boston.\nremove: Unrelated protected preference.\nprofile: Lives in NYC.\nnote: Likes cobalt for the demo.",
      existing
    );
    expect(await applyExtractedMemories(root, parsed, existing, now)).toEqual({
      added: ["Lives in NYC.", "[note] Likes cobalt for the demo."],
      removed: ["Lives in Boston."],
    });
    expect(await applyExtractedMemories(root, parsed, existing, now)).toEqual({
      added: [],
      removed: [],
    });
    const facts = await readMemoryTree(root);
    expect(facts.map(({ content }) => content)).toEqual([
      "Unrelated protected preference.",
      "Lives in NYC.",
      "[note] Likes cobalt for the demo.",
    ]);
    expect(facts.at(-1)).toMatchObject({
      tier: "note",
      importance: 0.5,
      sourcePath: "log/2026-09.md",
    });
    expect(await readFile(join(root, "profile.md"), "utf8")).toStartWith(
      "# Keep this heading\nManual prose."
    );
  } finally {
    await rm(root, { recursive: true, force: true });
  }
});

test("episode input uses absolute dates and retains important details after character 2000", () => {
  const user = `${"x".repeat(2100)} The final decision is cobalt.`;
  const prompt = buildEpisodeUserPrompt([
    { ts: Date.parse("2026-09-12T12:00:00Z"), user, agent: " Done. " },
  ]);
  expect(prompt).toContain("(2026-09-12)");
  expect(prompt).toContain(user);
  expect(prompt).toEndWith("OpenTeam: Done.");
  expect(parseEpisodeNarrative("  NONE \n")).toBeNull();
  expect(
    parseEpisodeNarrative(" Chose   cobalt.\nScheduled the review for September 20, 2026. ")
  ).toBe("Chose cobalt. Scheduled the review for September 20, 2026.");
  expect(buildExtractionUserPrompt("", "", [])).toBe(
    "Existing memory:\n(empty)\n\nLatest exchange:\nUser: (no message)\nAssistant: (no message)"
  );
  expect(
    getMemoryEpisodeInterval({
      OPENTEAM_MEMORY_EPISODE_INTERVAL: "3",
      SAND_MEMORY_EPISODE_INTERVAL: "9",
    })
  ).toBe(3);
});
